[window]

option_as_alt = "OnlyLeft"

[keyboard]

bindings = [
  # To make C-/ works like C-_ in Emacs
  { key = "Slash", mods = "Control", chars = "\u001f" }
]

[font]

size = 14
normal = { family = "Andale Mono", style = "Regular" }
